version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_api-gateway
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    # --save 60 1 означает: сохранять данные на диск каждые 60 секунд, если было хотя бы 1 изменение
    #  нужно, чтобы при перезагрузке контейнера забаненные пользователи не разбанились крч
    volumes:
      - ./redis_data:/data

  # веб интерфейс для просмотра данных в Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_api
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis